from PyQt5 import QtWidgets, QtCore, QtGui
from View.UserWindow import UserWindow


class FanWindow(UserWindow):

    def __init__(self, controller):
        super().__init__(controller)
        self.setWindowTitle('FanScreen')
        self.setGeometry(100, 100, 564, 537)
        self.tabWidget = QtWidgets.QTabWidget(self)
        self.tabWidget.setGeometry(QtCore.QRect(10, 20, 541, 456))
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.MainTab = QtWidgets.QWidget()
        self.MainTab.setObjectName("MainTab")
        self.background_pic = QtWidgets.QLabel(self.MainTab)
        self.background_pic.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.background_pic.setText("")
        self.background_pic.setPixmap(QtGui.QPixmap("../Resources/thailand.jpg"))
        self.background_pic.setScaledContents(True)
        self.background_pic.setObjectName("background_pic")
        self.followPageBtn = QtWidgets.QPushButton(self.MainTab)
        self.followPageBtn.setGeometry(QtCore.QRect(220, 270, 91, 21))
        self.followPageBtn.setObjectName("followPageBtn")
        self.followPageBtn.clicked.connect(self.followPage)
        self.followGameBtn = QtWidgets.QPushButton(self.MainTab)
        self.followGameBtn.setGeometry(QtCore.QRect(220, 300, 91, 23))
        self.followGameBtn.setObjectName("followGameBtn")
        self.followGameBtn.clicked.connect(self.followGame)
        self.showHistoryBtn = QtWidgets.QPushButton(self.MainTab)
        self.showHistoryBtn.setGeometry(QtCore.QRect(220, 330, 91, 23))
        self.showHistoryBtn.setObjectName("showHistoryBtn")
        self.showHistoryBtn.clicked.connect(self.showHistory)
        self.showComplaintsBtn = QtWidgets.QPushButton(self.MainTab)
        self.showComplaintsBtn.setGeometry(QtCore.QRect(220, 360, 91, 23))
        self.showComplaintsBtn.setObjectName("showComplaintsBtn")
        self.showComplaintsBtn.clicked.connect(self.showComplaints)
        self.editInfoBtn = QtWidgets.QPushButton(self.MainTab)
        self.editInfoBtn.setGeometry(QtCore.QRect(220, 240, 91, 21))
        self.editInfoBtn.setObjectName("editInfoBtn")
        self.editInfoBtn.clicked.connect(self.editInfo)
        self.tabWidget.addTab(self.MainTab, "")
        self.followPageTab = QtWidgets.QWidget()
        self.followPageTab.setObjectName("followPageTab")
        self.searchBtn = QtWidgets.QPushButton(self.followPageTab)
        self.searchBtn.setGeometry(QtCore.QRect(180, 100, 151, 23))
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setObjectName("searchBtn")
        self.SearchLabel = QtWidgets.QLabel(self.followPageTab)
        self.SearchLabel.setGeometry(QtCore.QRect(200, 10, 131, 31))
        self.SearchLabel.setObjectName("SearchLabel")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.followPageTab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(180, 40, 151, 61))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nameLabel_3 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.nameLabel_3.setObjectName("nameLabel_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel_3)
        self.nameLineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.nameLineEdit_3.setObjectName("nameLineEdit_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit_3)
        self.roleLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.roleLabel.setObjectName("roleLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.roleLabel)
        self.roleComboBox = QtWidgets.QComboBox(self.formLayoutWidget_4)
        self.roleComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.roleComboBox.setObjectName("roleComboBox")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.roleComboBox.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.roleComboBox)
        self.background_pic_2 = QtWidgets.QLabel(self.followPageTab)
        self.background_pic_2.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.background_pic_2.setText("")
        self.background_pic_2.setPixmap(QtGui.QPixmap("../Resources/thailand.jpg"))
        self.background_pic_2.setScaledContents(True)
        self.background_pic_2.setObjectName("background_pic_2")
        self.background_pic_2.raise_()
        self.searchBtn.raise_()
        self.SearchLabel.raise_()
        self.formLayoutWidget_4.raise_()
        self.tabWidget.addTab(self.followPageTab, "")
        self.followGameTab = QtWidgets.QWidget()
        self.followGameTab.setObjectName("followGameTab")
        self.background_pic_3 = QtWidgets.QLabel(self.followGameTab)
        self.background_pic_3.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.background_pic_3.setText("")
        self.background_pic_3.setPixmap(QtGui.QPixmap("../Resources/thailand.jpg"))
        self.background_pic_3.setScaledContents(True)
        self.background_pic_3.setObjectName("background_pic_3")
        self.tableWidget_showFixtures = QtWidgets.QTableWidget(self.followGameTab)
        self.tableWidget_showFixtures.setGeometry(QtCore.QRect(110, 20, 302, 371))
        self.tableWidget_showFixtures.setStyleSheet("background-color: transparent;")
        self.tableWidget_showFixtures.setShowGrid(True)
        self.tableWidget_showFixtures.setObjectName("tableWidget_showFixtures")
        self.tableWidget_showFixtures.setColumnCount(3)
        self.tableWidget_showFixtures.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_showFixtures.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_showFixtures.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_showFixtures.setHorizontalHeaderItem(2, item)
        self.followGameBtn2 = QtWidgets.QPushButton(self.followGameTab)
        self.followGameBtn2.setGeometry(QtCore.QRect(430, 10, 91, 23))
        self.followGameBtn2.setObjectName("followGameBtn2")
        self.background_pic_3.raise_()
        self.followGameBtn2.raise_()
        self.tableWidget_showFixtures.raise_()
        self.tabWidget.addTab(self.followGameTab, "")
        self.complaintsTab = QtWidgets.QWidget()
        self.complaintsTab.setObjectName("complaintsTab")
        self.background_pic_4 = QtWidgets.QLabel(self.complaintsTab)
        self.background_pic_4.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.background_pic_4.setText("")
        self.background_pic_4.setPixmap(QtGui.QPixmap("../Resources/thailand.jpg"))
        self.background_pic_4.setScaledContents(True)
        self.background_pic_4.setObjectName("background_pic_4")
        self.tableWidget = QtWidgets.QTableWidget(self.complaintsTab)
        self.tableWidget.setGeometry(QtCore.QRect(110, 20, 310, 401))
        self.tableWidget.setStyleSheet("background-color: transparent;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tabWidget.addTab(self.complaintsTab, "")
        self.searchHistoryTab = QtWidgets.QWidget()
        self.searchHistoryTab.setObjectName("searchHistoryTab")
        self.background_pic_5 = QtWidgets.QLabel(self.searchHistoryTab)
        self.background_pic_5.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.background_pic_5.setText("")
        self.background_pic_5.setPixmap(QtGui.QPixmap("../Resources/thailand.jpg"))
        self.background_pic_5.setScaledContents(True)
        self.background_pic_5.setObjectName("background_pic_5")
        self.tableWidget_searchHistory = QtWidgets.QTableWidget(self.searchHistoryTab)
        self.tableWidget_searchHistory.setGeometry(QtCore.QRect(110, 20, 302, 371))
        self.tableWidget_searchHistory.setStyleSheet("background-color: transparent;")
        self.tableWidget_searchHistory.setObjectName("tableWidget_searchHistory")
        self.tableWidget_searchHistory.setColumnCount(1)
        self.tableWidget_searchHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.tableWidget_searchHistory.setHorizontalHeaderItem(0, item)
        self.pushButton = QtWidgets.QPushButton(self.searchHistoryTab)
        self.pushButton.setGeometry(QtCore.QRect(430, 10, 91, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.searchHistoryTab, "")
        self.editInfoTab = QtWidgets.QWidget()
        self.editInfoTab.setObjectName("editInfoTab")
        self.formLayoutWidget = QtWidgets.QWidget(self.editInfoTab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(130, 60, 251, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.usernameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.usernameLabel.setObjectName("usernameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.usernameLabel)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.usernameLineEdit)
        self.passwordLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.passwordLabel.setObjectName("passwordLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.passwordLabel)
        self.passwordLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordLineEdit)
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.birthDateLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.birthDateLabel.setObjectName("birthDateLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.birthDateLabel)
        self.birthDateDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.birthDateDateEdit.setObjectName("birthDateDateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.birthDateDateEdit)
        self.editInfoLabel = QtWidgets.QLabel(self.editInfoTab)
        self.editInfoLabel.setGeometry(QtCore.QRect(110, 10, 301, 41))
        self.editInfoLabel.setObjectName("editInfoLabel")
        self.saveInfoBtn = QtWidgets.QPushButton(self.editInfoTab)
        self.saveInfoBtn.setGeometry(QtCore.QRect(130, 190, 251, 23))
        self.saveInfoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveInfoBtn.setObjectName("saveInfoBtn")
        self.background_pic_6 = QtWidgets.QLabel(self.editInfoTab)
        self.background_pic_6.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.background_pic_6.setText("")
        self.background_pic_6.setPixmap(QtGui.QPixmap("../Resources/thailand.jpg"))
        self.background_pic_6.setScaledContents(True)
        self.background_pic_6.setObjectName("background_pic_6")
        self.background_pic_6.raise_()
        self.formLayoutWidget.raise_()
        self.editInfoLabel.raise_()
        self.saveInfoBtn.raise_()
        self.tabWidget.addTab(self.editInfoTab, "")
        self.helloFanLabel = QtWidgets.QLabel(self)
        self.helloFanLabel.setGeometry(QtCore.QRect(190, -20, 151, 61))
        self.helloFanLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.helloFanLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.helloFanLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.helloFanLabel.setObjectName("helloFanLabel")
        self.logoutBtn = QtWidgets.QPushButton(self)
        self.logoutBtn.setGeometry(QtCore.QRect(414, 500, 131, 23))
        self.logoutBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logoutBtn.setObjectName("logoutBtn")
        self.helloFanLabel.raise_()
        self.tabWidget.raise_()
        self.logoutBtn.raise_()
        self.logo = QtWidgets.QLabel(self)
        self.logo.setGeometry(QtCore.QRect(20, 420, 101, 101))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Resources/football federation.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)

        self.connect_buttons()

        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.followPageBtn.setText(_translate("Form", "Follow Page"))
        self.followGameBtn.setText(_translate("Form", "Follow Game"))
        self.showHistoryBtn.setText(_translate("Form", "Show History"))
        self.showComplaintsBtn.setText(_translate("Form", "Show Complaints"))
        self.editInfoBtn.setText(_translate("Form", "Edit Information"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MainTab), _translate("Form", "Main"))
        self.searchBtn.setText(_translate("Form", "Search"))
        self.SearchLabel.setText(_translate("Form",
                                            "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Search Page</span></p></body></html>"))
        self.nameLabel_3.setText(_translate("Form", "name:"))
        self.roleLabel.setText(_translate("Form", "role:"))
        self.roleComboBox.setItemText(0, _translate("Form", "choose role.."))
        self.roleComboBox.setItemText(1, _translate("Form", "Team"))
        self.roleComboBox.setItemText(2, _translate("Form", "Player"))
        self.roleComboBox.setItemText(3, _translate("Form", "Coach"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.followPageTab), _translate("Form", "followPage"))
        item = self.tableWidget_showFixtures.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Home Team"))
        item = self.tableWidget_showFixtures.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Away Team"))
        item = self.tableWidget_showFixtures.horizontalHeaderItem(2)
        item.setText(_translate("Form", "GameDate"))
        self.followGameBtn2.setText(_translate("Form", "Follow Game"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.followGameTab), _translate("Form", "followGame"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Complaint ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Page"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Response"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.complaintsTab), _translate("Form", "complaints"))
        item = self.tableWidget_searchHistory.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Search History"))
        self.pushButton.setText(_translate("Form", "Show History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchHistoryTab), _translate("Form", "searchHistory"))
        self.usernameLabel.setText(_translate("Form", "username:"))
        self.passwordLabel.setText(_translate("Form", "password:"))
        self.nameLabel.setText(_translate("Form", "name:"))
        self.birthDateLabel.setText(_translate("Form", "birth date:"))
        self.editInfoLabel.setText(_translate("Form",
                                              "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Edit your personal information</span></p></body></html>"))
        self.saveInfoBtn.setText(_translate("Form", "Save Info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.editInfoTab), _translate("Form", "editInfo"))
        self.helloFanLabel.setText(_translate("Form",
                                              "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Hello Fan</span></p></body></html>"))
        self.logoutBtn.setText(_translate("Form", "Logout"))

    def followPage(self):
        self.tabWidget.setCurrentIndex(1)

    def followGame(self):
        self.tabWidget.setCurrentIndex(2)

    def editInfo(self):
        self.tabWidget.setCurrentIndex(5)

    def showHistory(self):
        self.tabWidget.setCurrentIndex(4)

    def showComplaints(self):
        self.tabWidget.setCurrentIndex(3)

    def connect_buttons(self):
        self.logoutBtn.clicked.connect(self.controller.user_logout)
        pass