from PyQt5 import QtWidgets, QtCore, QtGui
from View.UserWindow import UserWindow


class SystemAdminWindow(UserWindow):

    def __init__(self, controller):
        super().__init__(controller)
        self.setWindowTitle('SystemAdmin')
        self.setGeometry(100, 100, 564, 537)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setObjectName("widget")
        self.helloSystemAdmin = QtWidgets.QLabel(self.widget)
        self.helloSystemAdmin.setGeometry(QtCore.QRect(150, 0, 251, 41))
        self.helloSystemAdmin.setObjectName("helloSystemAdmin")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 30, 521, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.Main = QtWidgets.QWidget()
        self.Main.setObjectName("Main")
        self.closeTeamBtn = QtWidgets.QPushButton(self.Main)
        self.closeTeamBtn.setGeometry(QtCore.QRect(220, 60, 75, 23))
        self.closeTeamBtn.setObjectName("closeTeamBtn")
        self.closeTeamBtn.clicked.connect(self.showTeams)
        self.removeUserBtn = QtWidgets.QPushButton(self.Main)
        self.removeUserBtn.setGeometry(QtCore.QRect(220, 90, 75, 23))
        self.removeUserBtn.setObjectName("removeUserBtn")
        self.removeUserBtn.clicked.connect(self.showUsers)
        self.complaintsBtn = QtWidgets.QPushButton(self.Main)
        self.complaintsBtn.setGeometry(QtCore.QRect(220, 120, 75, 23))
        self.complaintsBtn.setObjectName("complaintsBtn")
        self.complaintsBtn.clicked.connect(self.showComplaints)
        self.showLoggerBtn = QtWidgets.QPushButton(self.Main)
        self.showLoggerBtn.setGeometry(QtCore.QRect(220, 150, 75, 23))
        self.showLoggerBtn.setObjectName("showLoggerBtn")
        self.showLoggerBtn.clicked.connect(self.showLogger)
        self.buildRecoSysBtn = QtWidgets.QPushButton(self.Main)
        self.buildRecoSysBtn.setGeometry(QtCore.QRect(190, 180, 131, 23))
        self.buildRecoSysBtn.setObjectName("buildRecoSysBtn")
        self.buildRecoSysBtn.clicked.connect(self.showRecoSys)
        self.optionsLbl = QtWidgets.QLabel(self.Main)
        self.optionsLbl.setGeometry(QtCore.QRect(180, 20, 151, 31))
        self.optionsLbl.setObjectName("optionsLbl")
        self.picMainTab = QtWidgets.QLabel(self.Main)
        self.picMainTab.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.picMainTab.setText("")
        self.picMainTab.setPixmap(QtGui.QPixmap("../Resources/greenland.jpg"))
        self.picMainTab.setScaledContents(True)
        self.picMainTab.setObjectName("picMainTab")
        self.picMainTab.lower()
        self.tabWidget.addTab(self.Main, "")
        self.teams = QtWidgets.QWidget()
        self.teams.setObjectName("teams")
        self.teamTable = QtWidgets.QTableWidget(self.teams)
        self.teamTable.setGeometry(QtCore.QRect(30, 30, 256, 321))
        self.teamTable.setStyleSheet("background-color: transparent")
        self.teamTable.setObjectName("teamTable")
        self.teamTable.setColumnCount(1)
        self.teamTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.teamTable.setHorizontalHeaderItem(0, item)
        self.closeTeamBtn_2 = QtWidgets.QPushButton(self.teams)
        self.closeTeamBtn_2.setGeometry(QtCore.QRect(380, 30, 75, 23))
        self.closeTeamBtn_2.setObjectName("closeTeamBtn_2")
        self.picTeamTab = QtWidgets.QLabel(self.teams)
        self.picTeamTab.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.picTeamTab.setText("")
        self.picTeamTab.setPixmap(QtGui.QPixmap("../Resources/greenland.jpg"))
        self.picTeamTab.setScaledContents(True)
        self.picTeamTab.setObjectName("picTeamTab")
        self.picTeamTab.lower()
        self.tabWidget.addTab(self.teams, "")
        self.users = QtWidgets.QWidget()
        self.users.setObjectName("users")
        self.usersTable = QtWidgets.QTableWidget(self.users)
        self.usersTable.setGeometry(QtCore.QRect(30, 30, 311, 321))
        self.usersTable.setStyleSheet("background-color: transparent")
        self.usersTable.setObjectName("usersTable")
        self.usersTable.setColumnCount(3)
        self.usersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.usersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.usersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.usersTable.setHorizontalHeaderItem(2, item)
        self.removeUserBtn_2 = QtWidgets.QPushButton(self.users)
        self.removeUserBtn_2.setGeometry(QtCore.QRect(400, 30, 75, 23))
        self.removeUserBtn_2.setObjectName("removeUserBtn_2")
        self.picUserTab = QtWidgets.QLabel(self.users)
        self.picUserTab.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.picUserTab.setText("")
        self.picUserTab.setPixmap(QtGui.QPixmap("../Resources/greenland.jpg"))
        self.picUserTab.setScaledContents(True)
        self.picUserTab.setObjectName("picUserTab")
        self.picUserTab.lower()
        self.tabWidget.addTab(self.users, "")
        self.complaints = QtWidgets.QWidget()
        self.complaints.setObjectName("complaints")
        self.complaintsTable = QtWidgets.QTableWidget(self.complaints)
        self.complaintsTable.setGeometry(QtCore.QRect(30, 30, 406, 211))
        self.complaintsTable.setStyleSheet("background-color: transparent")
        self.complaintsTable.setObjectName("complaintsTable")
        self.complaintsTable.setColumnCount(4)
        self.complaintsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.complaintsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaintsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaintsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.complaintsTable.setHorizontalHeaderItem(3, item)
        self.respondBtn = QtWidgets.QPushButton(self.complaints)
        self.respondBtn.setGeometry(QtCore.QRect(190, 260, 91, 21))
        self.respondBtn.setObjectName("respondBtn")
        self.picComplaintsTab = QtWidgets.QLabel(self.complaints)
        self.picComplaintsTab.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.picComplaintsTab.setText("")
        self.picComplaintsTab.setPixmap(QtGui.QPixmap("../Resources/greenland.jpg"))
        self.picComplaintsTab.setScaledContents(True)
        self.picComplaintsTab.setObjectName("picComplaintsTab")
        self.picComplaintsTab.lower()
        self.tabWidget.addTab(self.complaints, "")
        self.logger = QtWidgets.QWidget()
        self.logger.setObjectName("logger")
        self.loggerTable = QtWidgets.QTableWidget(self.logger)
        self.loggerTable.setGeometry(QtCore.QRect(30, 30, 301, 341))
        self.loggerTable.setStyleSheet("background-color: transparent")
        self.loggerTable.setObjectName("loggerTable")
        self.loggerTable.setColumnCount(2)
        self.loggerTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.loggerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.loggerTable.setHorizontalHeaderItem(1, item)
        self.picLoggerTab = QtWidgets.QLabel(self.logger)
        self.picLoggerTab.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.picLoggerTab.setText("")
        self.picLoggerTab.setPixmap(QtGui.QPixmap("../Resources/greenland.jpg"))
        self.picLoggerTab.setScaledContents(True)
        self.picLoggerTab.setObjectName("picLoggerTab")
        self.picLoggerTab.lower()
        self.tabWidget.addTab(self.logger, "")
        self.recommendationSystem = QtWidgets.QWidget()
        self.recommendationSystem.setObjectName("recommendationSystem")
        self.recSysBtn = QtWidgets.QPushButton(self.recommendationSystem)
        self.recSysBtn.setGeometry(QtCore.QRect(160, 30, 181, 41))
        self.recSysBtn.setObjectName("recSysBtn")
        self.picRecSysTab = QtWidgets.QLabel(self.recommendationSystem)
        self.picRecSysTab.setGeometry(QtCore.QRect(0, 0, 534, 431))
        self.picRecSysTab.setText("")
        self.picRecSysTab.setPixmap(QtGui.QPixmap("../Resources/greenland.jpg"))
        self.picRecSysTab.setScaledContents(True)
        self.picRecSysTab.setObjectName("picRecSysTab")
        self.picRecSysTab.lower()
        self.tabWidget.addTab(self.recommendationSystem, "")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(450, 420, 101, 101))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../Resources/football federation.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.backBtn = QtWidgets.QPushButton(self)
        self.backBtn.setGeometry(QtCore.QRect(25, 495, 95, 23))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setObjectName("backBtn")

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        self.connect_buttons()

        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("SystemAdmin", "MainWindow"))
        self.helloSystemAdmin.setText(_translate("SystemAdmin",
                                                 "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Hello System Admin</span></p></body></html>"))
        self.closeTeamBtn.setText(_translate("SystemAdmin", "Teams"))
        self.removeUserBtn.setText(_translate("SystemAdmin", "Users"))
        self.complaintsBtn.setText(_translate("SystemAdmin", "Complaints"))
        self.showLoggerBtn.setText(_translate("SystemAdmin", "Logger"))
        self.buildRecoSysBtn.setText(_translate("SystemAdmin", "Recommendation System"))
        self.optionsLbl.setText(_translate("SystemAdmin",
                                           "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Options</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Main), _translate("SystemAdmin", "Main"))
        item = self.teamTable.horizontalHeaderItem(0)
        item.setText(_translate("SystemAdmin", "Team"))
        self.closeTeamBtn_2.setText(_translate("SystemAdmin", "Close Team"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teams), _translate("SystemAdmin", "Teams"))
        item = self.usersTable.horizontalHeaderItem(0)
        item.setText(_translate("SystemAdmin", "New Column"))
        item = self.usersTable.horizontalHeaderItem(1)
        item.setText(_translate("SystemAdmin", "Role"))
        item = self.usersTable.horizontalHeaderItem(2)
        item.setText(_translate("SystemAdmin", "Name"))
        self.removeUserBtn_2.setText(_translate("SystemAdmin", "Remove User"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.users), _translate("SystemAdmin", "Users"))
        item = self.complaintsTable.horizontalHeaderItem(0)
        item.setText(_translate("SystemAdmin", "Complaint ID"))
        item = self.complaintsTable.horizontalHeaderItem(1)
        item.setText(_translate("SystemAdmin", "Page"))
        item = self.complaintsTable.horizontalHeaderItem(2)
        item.setText(_translate("SystemAdmin", "Response"))
        item = self.complaintsTable.horizontalHeaderItem(3)
        item.setText(_translate("SystemAdmin", "Complainer"))
        self.respondBtn.setToolTip(
            _translate("SystemAdmin", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.respondBtn.setText(_translate("SystemAdmin", "Respond"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.complaints), _translate("SystemAdmin", "Complaints"))
        item = self.loggerTable.horizontalHeaderItem(0)
        item.setText(_translate("SystemAdmin", "Action"))
        item = self.loggerTable.horizontalHeaderItem(1)
        item.setText(_translate("SystemAdmin", "Successful"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logger), _translate("SystemAdmin", "Logger"))
        self.recSysBtn.setText(_translate("SystemAdmin", "Build Recommendation System"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.recommendationSystem),
                                  _translate("SystemAdmin", "Recommendation System"))
        self.backBtn.setText(_translate("MainWindow", "Logout"))


    def showTeams(self):
        self.tabWidget.setCurrentIndex(1)

    def showUsers(self):
        self.tabWidget.setCurrentIndex(2)

    def showComplaints(self):
        self.tabWidget.setCurrentIndex(3)

    def showLogger(self):
        self.tabWidget.setCurrentIndex(4)

    def showRecoSys(self):
        self.tabWidget.setCurrentIndex(5)

    def connect_buttons(self):
        self.backBtn.clicked.connect(self.controller.user_logout)
        pass